import { prisma } from "@/lib/prisma";
import { sendEmail } from "@/lib/email";

interface FollowUpResult {
  processed: number;
  emailsSent: number;
  tasksCreated: number;
  errors: string[];
  details: Array<{
    quoteId: string;
    quoteRef: string;
    companyName: string;
    action: string;
    followUpCount: number;
  }>;
}

async function getNickUserId(): Promise<string | null> {
  const nick = await prisma.user.findFirst({
    where: { role: "sales" },
    select: { id: true },
  });
  return nick?.id ?? null;
}

export async function runQuoteFollowUp(): Promise<FollowUpResult> {
  const result: FollowUpResult = {
    processed: 0,
    emailsSent: 0,
    tasksCreated: 0,
    errors: [],
    details: [],
  };

  console.log("[QuoteFollowUp] Starting quote follow-up engine run...");

  try {
    const now = new Date();
    const fortyEightHoursAgo = new Date(now.getTime() - 48 * 60 * 60 * 1000);
    const fiveDaysAgo = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000);

    const nickUserId = await getNickUserId();

    if (!nickUserId) {
      result.errors.push("Could not find a sales user (Nick) to assign tasks to");
      console.error("[QuoteFollowUp] No sales user found");
      return result;
    }

    // --- Stage 1: 48-hour follow-up (followUpCount = 0) ---
    const stage1Quotes = await prisma.quote.findMany({
      where: {
        status: "sent",
        followUpCount: 0,
        sentAt: {
          lt: fortyEightHoursAgo,
          not: null,
        },
      },
    });

    console.log(
      `[QuoteFollowUp] Stage 1 (48hr): Found ${stage1Quotes.length} quotes`
    );

    for (const quote of stage1Quotes) {
      result.processed++;

      try {
        await sendEmail({
          from: "nick",
          to: quote.contactEmail,
          subject: `Following up on your Signature Cleans quote - ${quote.companyName}`,
          html: `<p>Hi ${quote.contactName},</p>
<p>I wanted to follow up on the cleaning quote I sent over for <strong>${quote.companyName}</strong> (Ref: ${quote.quoteRef}).</p>
<p>I understand you may be busy, but I'd love to hear your thoughts. Do you have any questions about the proposal, or would you like to discuss anything further?</p>
<p>I'm happy to jump on a quick call at your convenience to walk through the details.</p>
<p>Looking forward to hearing from you.</p>
<p>Best regards,<br/>Nick<br/>Signature Cleans</p>`,
        });

        await prisma.quote.update({
          where: { id: quote.id },
          data: {
            followUpCount: 1,
            lastFollowUpAt: now,
          },
        });

        // Create task for Nick
        await prisma.task.create({
          data: {
            title: `Follow up on quote: ${quote.companyName}`,
            description: `Quote ${quote.quoteRef} was sent and a 48-hour follow-up email has been automatically sent. Please follow up personally if no response.`,
            assignedTo: nickUserId,
            createdBy: nickUserId,
            priority: "medium",
            dueDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000),
            leadId: quote.leadId,
            dealId: quote.dealId,
            autoGenerated: true,
            sourceWorkflow: "quote_follow_up",
          },
        });

        result.emailsSent++;
        result.tasksCreated++;
        result.details.push({
          quoteId: quote.id,
          quoteRef: quote.quoteRef,
          companyName: quote.companyName,
          action: "48hr follow-up sent + task created",
          followUpCount: 1,
        });

        console.log(
          `[QuoteFollowUp] Stage 1: Sent 48hr follow-up for ${quote.companyName} (${quote.quoteRef})`
        );
      } catch (err) {
        const errorMessage =
          err instanceof Error ? err.message : "Unknown error";
        result.errors.push(
          `Stage 1 error for ${quote.quoteRef}: ${errorMessage}`
        );
        console.error(
          `[QuoteFollowUp] Stage 1 error for ${quote.quoteRef}:`,
          err
        );
      }
    }

    // --- Stage 2: Day-5 follow-up with case study mention (followUpCount = 1) ---
    const stage2Quotes = await prisma.quote.findMany({
      where: {
        status: "sent",
        followUpCount: 1,
        lastFollowUpAt: {
          lt: fiveDaysAgo,
          not: null,
        },
      },
    });

    console.log(
      `[QuoteFollowUp] Stage 2 (Day-5): Found ${stage2Quotes.length} quotes`
    );

    for (const quote of stage2Quotes) {
      result.processed++;

      try {
        await sendEmail({
          from: "nick",
          to: quote.contactEmail,
          subject: `Quick update & case study - ${quote.companyName} cleaning quote`,
          html: `<p>Hi ${quote.contactName},</p>
<p>I hope you're well. I wanted to touch base again regarding the cleaning quote for <strong>${quote.companyName}</strong> (Ref: ${quote.quoteRef}).</p>
<p>I thought you might find it useful to hear how we've helped similar businesses. One of our clients in a comparable setting saw a significant improvement in cleanliness standards within the first month, with consistently positive feedback from their team.</p>
<p>We pride ourselves on reliability and quality, and I'd love the opportunity to demonstrate that for ${quote.companyName}.</p>
<p>Would you be open to a brief conversation this week? I'm flexible with timing.</p>
<p>Best regards,<br/>Nick<br/>Signature Cleans</p>`,
        });

        await prisma.quote.update({
          where: { id: quote.id },
          data: {
            followUpCount: 2,
            lastFollowUpAt: now,
          },
        });

        result.emailsSent++;
        result.details.push({
          quoteId: quote.id,
          quoteRef: quote.quoteRef,
          companyName: quote.companyName,
          action: "Day-5 case study follow-up sent",
          followUpCount: 2,
        });

        console.log(
          `[QuoteFollowUp] Stage 2: Sent day-5 follow-up for ${quote.companyName} (${quote.quoteRef})`
        );
      } catch (err) {
        const errorMessage =
          err instanceof Error ? err.message : "Unknown error";
        result.errors.push(
          `Stage 2 error for ${quote.quoteRef}: ${errorMessage}`
        );
        console.error(
          `[QuoteFollowUp] Stage 2 error for ${quote.quoteRef}:`,
          err
        );
      }
    }

    // --- Stage 3: Day-10 final follow-up with pilot offer (followUpCount = 2) ---
    const stage3Quotes = await prisma.quote.findMany({
      where: {
        status: "sent",
        followUpCount: 2,
        lastFollowUpAt: {
          lt: fiveDaysAgo,
          not: null,
        },
      },
    });

    console.log(
      `[QuoteFollowUp] Stage 3 (Day-10): Found ${stage3Quotes.length} quotes`
    );

    for (const quote of stage3Quotes) {
      result.processed++;

      try {
        const pilotOffer = quote.applyPilotPricing
          ? `<p>As a reminder, the quote already includes our competitive pilot pricing to help you get started with minimal commitment.</p>`
          : `<p>I'd also like to offer you a <strong>pilot period</strong> at a reduced rate, so you can experience our service with no long-term commitment. It's a great way to see the Signature Cleans difference first-hand.</p>`;

        await sendEmail({
          from: "nick",
          to: quote.contactEmail,
          subject: `Final follow-up on your cleaning quote - ${quote.companyName}`,
          html: `<p>Hi ${quote.contactName},</p>
<p>I appreciate you may be very busy, so I'll keep this brief. This is my final follow-up regarding the cleaning quote for <strong>${quote.companyName}</strong> (Ref: ${quote.quoteRef}).</p>
${pilotOffer}
<p>If now isn't the right time, I completely understand. I'll keep your details on file and would be happy to revisit whenever suits you.</p>
<p>If you'd like to proceed or just have a chat, please don't hesitate to get in touch.</p>
<p>All the best,<br/>Nick<br/>Signature Cleans</p>`,
        });

        await prisma.quote.update({
          where: { id: quote.id },
          data: {
            followUpCount: 3,
            lastFollowUpAt: now,
          },
        });

        result.emailsSent++;
        result.details.push({
          quoteId: quote.id,
          quoteRef: quote.quoteRef,
          companyName: quote.companyName,
          action: "Day-10 final follow-up sent (pilot offer)",
          followUpCount: 3,
        });

        console.log(
          `[QuoteFollowUp] Stage 3: Sent day-10 final follow-up for ${quote.companyName} (${quote.quoteRef})`
        );
      } catch (err) {
        const errorMessage =
          err instanceof Error ? err.message : "Unknown error";
        result.errors.push(
          `Stage 3 error for ${quote.quoteRef}: ${errorMessage}`
        );
        console.error(
          `[QuoteFollowUp] Stage 3 error for ${quote.quoteRef}:`,
          err
        );
      }
    }

    // --- Stage 4: After 3 follow-ups with no response, create stalled task ---
    const stalledQuotes = await prisma.quote.findMany({
      where: {
        status: "sent",
        followUpCount: 3,
        lastFollowUpAt: {
          lt: fiveDaysAgo,
          not: null,
        },
      },
    });

    console.log(
      `[QuoteFollowUp] Stage 4 (Stalled): Found ${stalledQuotes.length} quotes`
    );

    for (const quote of stalledQuotes) {
      result.processed++;

      try {
        // Check if a stalled task already exists for this quote to avoid duplicates
        const existingTask = await prisma.task.findFirst({
          where: {
            sourceWorkflow: "quote_follow_up_stalled",
            leadId: quote.leadId,
            dealId: quote.dealId,
            status: { in: ["pending", "in_progress"] },
          },
        });

        if (existingTask) {
          result.details.push({
            quoteId: quote.id,
            quoteRef: quote.quoteRef,
            companyName: quote.companyName,
            action: "Stalled task already exists - skipped",
            followUpCount: 3,
          });
          continue;
        }

        await prisma.task.create({
          data: {
            title: `Quote stalled \u2014 consider pilot offer or personal call`,
            description: `Quote ${quote.quoteRef} for ${quote.companyName} has had 3 follow-up emails with no response. Consider making a personal phone call or offering a pilot arrangement.`,
            assignedTo: nickUserId,
            createdBy: nickUserId,
            priority: "high",
            dueDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000),
            leadId: quote.leadId,
            dealId: quote.dealId,
            autoGenerated: true,
            sourceWorkflow: "quote_follow_up_stalled",
          },
        });

        result.tasksCreated++;
        result.details.push({
          quoteId: quote.id,
          quoteRef: quote.quoteRef,
          companyName: quote.companyName,
          action: "Stalled task created",
          followUpCount: 3,
        });

        console.log(
          `[QuoteFollowUp] Stage 4: Created stalled task for ${quote.companyName} (${quote.quoteRef})`
        );
      } catch (err) {
        const errorMessage =
          err instanceof Error ? err.message : "Unknown error";
        result.errors.push(
          `Stage 4 error for ${quote.quoteRef}: ${errorMessage}`
        );
        console.error(
          `[QuoteFollowUp] Stage 4 error for ${quote.quoteRef}:`,
          err
        );
      }
    }
  } catch (err) {
    const errorMessage =
      err instanceof Error ? err.message : "Unknown error";
    result.errors.push(`Quote follow-up engine failed: ${errorMessage}`);
    console.error("[QuoteFollowUp] Fatal error:", err);
  }

  console.log(
    `[QuoteFollowUp] Complete — Processed: ${result.processed}, Emails sent: ${result.emailsSent}, Tasks created: ${result.tasksCreated}, Errors: ${result.errors.length}`
  );

  return result;
}
