import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import crypto from "crypto";

// Verify Calendly webhook signature if signing key is configured
function verifyCalendlySignature(
  payload: string,
  signature: string | null,
  secret: string
): boolean {
  if (!signature) return false;

  // Calendly sends signature in format: t=timestamp,v1=hash
  const parts = signature.split(",");
  const timestampPart = parts.find((p) => p.startsWith("t="));
  const signaturePart = parts.find((p) => p.startsWith("v1="));

  if (!timestampPart || !signaturePart) return false;

  const timestamp = timestampPart.slice(2);
  const expectedSignature = signaturePart.slice(3);

  const signedPayload = `${timestamp}.${payload}`;
  const computedSignature = crypto
    .createHmac("sha256", secret)
    .update(signedPayload)
    .digest("hex");

  return crypto.timingSafeEqual(
    Buffer.from(computedSignature),
    Buffer.from(expectedSignature)
  );
}

// POST /api/webhooks/calendly — Handle Calendly booking notifications
export async function POST(request: NextRequest) {
  try {
    const rawBody = await request.text();
    const webhookSecret = process.env.CALENDLY_WEBHOOK_SECRET;

    // Verify signature if webhook secret is configured
    if (webhookSecret) {
      const signature = request.headers.get("calendly-webhook-signature");
      if (!verifyCalendlySignature(rawBody, signature, webhookSecret)) {
        return NextResponse.json(
          { error: "Invalid webhook signature" },
          { status: 401 }
        );
      }
    }

    const body = JSON.parse(rawBody);

    // Only handle invitee.created events
    if (body.event !== "invitee.created") {
      return NextResponse.json({ message: "Event type ignored" });
    }

    const payload = body.payload;
    const inviteeEmail = payload?.email?.toLowerCase();
    const inviteeName = payload?.name || "";
    const eventStartTime = payload?.scheduled_event?.start_time;
    const eventEndTime = payload?.scheduled_event?.end_time;
    const eventName = payload?.scheduled_event?.name || "Calendly Meeting";
    const calendlyEventId = payload?.scheduled_event?.uri || payload?.uri;
    const cancelUrl = payload?.cancel_url || null;
    const rescheduleUrl = payload?.reschedule_url || null;

    if (!inviteeEmail) {
      return NextResponse.json(
        { error: "No invitee email in payload" },
        { status: 400 }
      );
    }

    // Look up Nick (sales user)
    const nickUser = await prisma.user.findFirst({ where: { role: "sales" } });

    if (!nickUser) {
      console.error("Calendly webhook: No sales user found");
      return NextResponse.json(
        { error: "No sales user configured" },
        { status: 500 }
      );
    }

    // Search for matching lead by contact email
    const lead = await prisma.lead.findFirst({
      where: {
        contactEmail: {
          equals: inviteeEmail,
          mode: "insensitive",
        },
        deletedAt: null,
      },
      include: {
        deals: {
          where: { deletedAt: null },
          orderBy: { createdAt: "desc" },
          take: 1,
        },
      },
    });

    if (lead) {
      const latestDeal = lead.deals[0] || null;

      // Create CalendarEvent linked to the lead's most recent deal
      const calendarEvent = await prisma.calendarEvent.create({
        data: {
          title: `Calendly: ${eventName}`,
          description: `Calendly booking with ${inviteeName} (${inviteeEmail})`,
          startTime: new Date(eventStartTime),
          endTime: new Date(eventEndTime),
          eventType: "meeting",
          calendlyEventId: calendlyEventId || undefined,
          calendlyCancelUrl: cancelUrl,
          calendlyRescheduleUrl: rescheduleUrl,
          status: "scheduled",
          createdBy: nickUser.id,
          ...(latestDeal && { dealId: latestDeal.id }),
        },
      });

      // Update lead: cadenceStatus to PausedMeeting, add tag
      const updatedTags = lead.tags.includes("Meeting Scheduled")
        ? lead.tags
        : [...lead.tags, "Meeting Scheduled"];

      await prisma.lead.update({
        where: { id: lead.id },
        data: {
          cadenceStatus: "PausedMeeting",
          tags: updatedTags,
        },
      });

      // Create Task for Nick
      await prisma.task.create({
        data: {
          title: `Confirm meeting with ${lead.companyName}`,
          description: `Calendly booking from ${inviteeName} (${inviteeEmail}). Event: ${eventName}`,
          assignedTo: nickUser.id,
          createdBy: nickUser.id,
          taskType: "business",
          priority: "high",
          status: "pending",
          autoGenerated: true,
          sourceWorkflow: "calendly_webhook",
          leadId: lead.id,
          ...(latestDeal && { dealId: latestDeal.id }),
        },
      });

      // Create Activity on the lead
      await prisma.activity.create({
        data: {
          activityType: "meeting",
          subject: `Calendly booking: ${eventName}`,
          body: `Meeting scheduled via Calendly with ${inviteeName} (${inviteeEmail}). Start: ${eventStartTime}, End: ${eventEndTime}`,
          leadId: lead.id,
          ...(latestDeal && { dealId: latestDeal.id }),
          performedBy: nickUser.id,
        },
      });

      return NextResponse.json({
        message: "Calendly booking processed",
        leadId: lead.id,
        calendarEventId: calendarEvent.id,
      });
    } else {
      // Lead NOT found - create unlinked CalendarEvent
      const calendarEvent = await prisma.calendarEvent.create({
        data: {
          title: `Calendly: ${eventName}`,
          description: `Calendly booking with ${inviteeName} (${inviteeEmail}) - no matching lead found`,
          startTime: new Date(eventStartTime),
          endTime: new Date(eventEndTime),
          eventType: "meeting",
          calendlyEventId: calendlyEventId || undefined,
          calendlyCancelUrl: cancelUrl,
          calendlyRescheduleUrl: rescheduleUrl,
          status: "scheduled",
          createdBy: nickUser.id,
        },
      });

      // Create notification for Nick about unknown contact
      await prisma.notification.create({
        data: {
          userId: nickUser.id,
          title: "Calendly booking from unknown contact",
          message: `Calendly booking from unknown contact: ${inviteeEmail} (${inviteeName}). Event: ${eventName}`,
          notificationType: "calendly_booking",
          entityType: "calendar_event",
          entityId: calendarEvent.id,
        },
      });

      return NextResponse.json({
        message: "Calendly booking processed (unknown contact)",
        calendarEventId: calendarEvent.id,
      });
    }
  } catch (error) {
    console.error("POST /api/webhooks/calendly error:", error);
    return NextResponse.json(
      { error: "Failed to process Calendly webhook" },
      { status: 500 }
    );
  }
}
