"use client";

import { useCallback, useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import {
  format,
  parseISO,
  isBefore,
  isToday as isDateToday,
  startOfWeek,
  startOfDay,
  endOfDay,
} from "date-fns";
import {
  DragDropContext,
  Droppable,
  Draggable,
  type DropResult,
} from "@hello-pangea/dnd";
import {
  CheckSquare,
  Plus,
  AlertTriangle,
  Clock,
  CheckCircle,
  ListTodo,
  Loader2,
  GripVertical,
  Briefcase,
  User,
  Filter,
  ArrowUpDown,
  Trash2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Separator } from "@/components/ui/separator";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface TaskRelation {
  id: string;
  name?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  companyName?: string;
  contactName?: string;
  contractName?: string;
  status?: string;
  avatarUrl?: string;
}

interface Task {
  id: string;
  title: string;
  description: string | null;
  assignedTo: string;
  createdBy: string;
  taskType: string;
  priority: string;
  status: string;
  dueDate: string | null;
  completedAt: string | null;
  autoGenerated: boolean;
  sourceWorkflow: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  assignee: TaskRelation | null;
  creator: TaskRelation | null;
  deal: TaskRelation | null;
  lead: TaskRelation | null;
  contact: TaskRelation | null;
  account: TaskRelation | null;
  contract: TaskRelation | null;
  subcontractor: TaskRelation | null;
  dealId: string | null;
  leadId: string | null;
  contactId: string | null;
  accountId: string | null;
  contractId: string | null;
}

interface LinkOption {
  id: string;
  label: string;
}

interface UserOption {
  id: string;
  name: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const PRIORITY_COLORS: Record<string, string> = {
  urgent: "bg-red-100 text-red-700 border-red-300 dark:bg-red-900/30 dark:text-red-300 dark:border-red-700",
  high: "bg-orange-100 text-orange-700 border-orange-300 dark:bg-orange-900/30 dark:text-orange-300 dark:border-orange-700",
  medium: "bg-blue-100 text-blue-700 border-blue-300 dark:bg-blue-900/30 dark:text-blue-300 dark:border-blue-700",
  low: "bg-gray-100 text-gray-600 border-gray-300 dark:bg-gray-900/30 dark:text-gray-300 dark:border-gray-700",
};

const STATUS_LABELS: Record<string, string> = {
  pending: "Pending",
  in_progress: "In Progress",
  completed: "Completed",
  cancelled: "Cancelled",
};

const PRIORITY_LABELS: Record<string, string> = {
  urgent: "Urgent",
  high: "High",
  medium: "Medium",
  low: "Low",
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getLinkedRecordLabel(task: Task): { type: string; name: string } | null {
  if (task.deal) return { type: "Deal", name: task.deal.name || "" };
  if (task.lead) return { type: "Lead", name: task.lead.companyName || task.lead.contactName || "" };
  if (task.contact) {
    const parts = [task.contact.firstName, task.contact.lastName].filter(Boolean);
    return { type: "Contact", name: parts.join(" ") };
  }
  if (task.account) return { type: "Account", name: task.account.name || "" };
  if (task.contract) return { type: "Contract", name: task.contract.contractName || "" };
  return null;
}

function isOverdue(task: Task): boolean {
  if (!task.dueDate) return false;
  if (task.status === "completed" || task.status === "cancelled") return false;
  return isBefore(parseISO(task.dueDate), startOfDay(new Date()));
}

function isDueToday(task: Task): boolean {
  if (!task.dueDate) return false;
  if (task.status === "completed" || task.status === "cancelled") return false;
  return isDateToday(parseISO(task.dueDate));
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function TasksPageClient() {
  const { data: session } = useSession();
  const { toast } = useToast();

  // Tab
  const [activeTab, setActiveTab] = useState("business");

  // Business tasks data
  const [businessTasks, setBusinessTasks] = useState<Task[]>([]);
  const [businessLoading, setBusinessLoading] = useState(true);

  // Personal tasks data
  const [personalTasks, setPersonalTasks] = useState<Task[]>([]);
  const [personalLoading, setPersonalLoading] = useState(true);

  // Stats
  const [statsTotal, setStatsTotal] = useState(0);
  const [statsOverdue, setStatsOverdue] = useState(0);
  const [statsDueToday, setStatsDueToday] = useState(0);
  const [statsCompletedWeek, setStatsCompletedWeek] = useState(0);

  // Filters (business)
  const [filterAssignedTo, setFilterAssignedTo] = useState("all");
  const [filterStatus, setFilterStatus] = useState("all");
  const [filterPriority, setFilterPriority] = useState("all");
  const [filterOverdue, setFilterOverdue] = useState(false);
  const [sortBy, setSortBy] = useState("dueDate");
  const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc");

  // Create task dialog
  const [createOpen, setCreateOpen] = useState(false);
  const [formTitle, setFormTitle] = useState("");
  const [formDescription, setFormDescription] = useState("");
  const [formAssignedTo, setFormAssignedTo] = useState("");
  const [formPriority, setFormPriority] = useState("medium");
  const [formDueDate, setFormDueDate] = useState("");
  const [formDealId, setFormDealId] = useState("");
  const [formLeadId, setFormLeadId] = useState("");
  const [formContactId, setFormContactId] = useState("");
  const [formAccountId, setFormAccountId] = useState("");
  const [formContractId, setFormContractId] = useState("");
  const [saving, setSaving] = useState(false);

  // Personal to-do input
  const [newTodoText, setNewTodoText] = useState("");
  const [newTodoDueDate, setNewTodoDueDate] = useState("");
  const [addingTodo, setAddingTodo] = useState(false);

  // Link options
  const [deals, setDeals] = useState<LinkOption[]>([]);
  const [leads, setLeads] = useState<LinkOption[]>([]);
  const [contacts, setContacts] = useState<LinkOption[]>([]);
  const [accounts, setAccounts] = useState<LinkOption[]>([]);
  const [contractOptions, setContractOptions] = useState<LinkOption[]>([]);
  const [users, setUsers] = useState<UserOption[]>([]);

  const currentUserId = session?.user?.id;

  // ---------------------------------------------------------------------------
  // Fetch business tasks
  // ---------------------------------------------------------------------------

  const fetchBusinessTasks = useCallback(async () => {
    setBusinessLoading(true);
    try {
      const params = new URLSearchParams({
        taskType: "business",
        limit: "100",
        sortBy,
        sortOrder,
      });
      if (filterAssignedTo && filterAssignedTo !== "all") params.set("assignedTo", filterAssignedTo);
      if (filterStatus && filterStatus !== "all") params.set("status", filterStatus);
      if (filterPriority && filterPriority !== "all") params.set("priority", filterPriority);
      if (filterOverdue) params.set("overdue", "true");

      const res = await fetch(`/api/tasks?${params}`);
      if (!res.ok) throw new Error("Failed to fetch tasks");
      const json = await res.json();
      setBusinessTasks(json.data || []);
    } catch {
      toast({ title: "Error", description: "Could not load business tasks.", variant: "destructive" });
    } finally {
      setBusinessLoading(false);
    }
  }, [sortBy, sortOrder, filterAssignedTo, filterStatus, filterPriority, filterOverdue, toast]);

  // ---------------------------------------------------------------------------
  // Fetch personal tasks
  // ---------------------------------------------------------------------------

  const fetchPersonalTasks = useCallback(async () => {
    if (!currentUserId) return;
    setPersonalLoading(true);
    try {
      const params = new URLSearchParams({
        taskType: "personal",
        assignedTo: currentUserId,
        limit: "100",
        sortBy: "createdAt",
        sortOrder: "asc",
      });
      const res = await fetch(`/api/tasks?${params}`);
      if (!res.ok) throw new Error("Failed to fetch tasks");
      const json = await res.json();
      setPersonalTasks(json.data || []);
    } catch {
      toast({ title: "Error", description: "Could not load personal tasks.", variant: "destructive" });
    } finally {
      setPersonalLoading(false);
    }
  }, [currentUserId, toast]);

  // ---------------------------------------------------------------------------
  // Fetch stats
  // ---------------------------------------------------------------------------

  const fetchStats = useCallback(async () => {
    try {
      // Total active tasks
      const totalRes = await fetch("/api/tasks?limit=1&status=pending");
      const pendingRes = await fetch("/api/tasks?limit=1&status=in_progress");

      let total = 0;
      if (totalRes.ok) {
        const j = await totalRes.json();
        total += j.pagination?.total || 0;
      }
      if (pendingRes.ok) {
        const j = await pendingRes.json();
        total += j.pagination?.total || 0;
      }
      setStatsTotal(total);

      // Overdue
      const overdueRes = await fetch("/api/tasks?limit=1&overdue=true");
      if (overdueRes.ok) {
        const j = await overdueRes.json();
        setStatsOverdue(j.pagination?.total || 0);
      }

      // Due today
      const today = new Date();
      const todayStart = startOfDay(today).toISOString();
      const todayEnd = endOfDay(today).toISOString();
      const dueTodayRes = await fetch(
        `/api/tasks?limit=1&dueDateFrom=${todayStart}&dueDateTo=${todayEnd}`
      );
      if (dueTodayRes.ok) {
        const j = await dueTodayRes.json();
        setStatsDueToday(j.pagination?.total || 0);
      }

      // Completed this week
      const weekStart = startOfWeek(today, { weekStartsOn: 1 });
      const completedRes = await fetch(
        `/api/tasks?limit=1&status=completed&dueDateFrom=${weekStart.toISOString()}`
      );
      if (completedRes.ok) {
        const j = await completedRes.json();
        setStatsCompletedWeek(j.pagination?.total || 0);
      }
    } catch {
      // Silently fail for stats
    }
  }, []);

  // ---------------------------------------------------------------------------
  // Fetch link options
  // ---------------------------------------------------------------------------

  const fetchLinkOptions = useCallback(async () => {
    try {
      const [dealsRes, leadsRes, contactsRes, accountsRes, contractsRes] = await Promise.all([
        fetch("/api/deals?limit=100"),
        fetch("/api/leads?limit=100"),
        fetch("/api/contacts?limit=100"),
        fetch("/api/accounts?limit=100"),
        fetch("/api/contracts?limit=100"),
      ]);

      if (dealsRes.ok) {
        const d = await dealsRes.json();
        const items = d.data || d;
        setDeals(
          (Array.isArray(items) ? items : []).map((x: { id: string; name: string }) => ({
            id: x.id,
            label: x.name,
          }))
        );
      }

      if (leadsRes.ok) {
        const l = await leadsRes.json();
        const items = l.data || l;
        setLeads(
          (Array.isArray(items) ? items : []).map(
            (x: { id: string; companyName: string }) => ({
              id: x.id,
              label: x.companyName,
            })
          )
        );
      }

      if (contactsRes.ok) {
        const c = await contactsRes.json();
        const items = c.data || c;
        setContacts(
          (Array.isArray(items) ? items : []).map(
            (x: { id: string; firstName?: string; lastName: string }) => ({
              id: x.id,
              label: [x.firstName, x.lastName].filter(Boolean).join(" "),
            })
          )
        );
      }

      if (accountsRes.ok) {
        const a = await accountsRes.json();
        const items = a.data || a;
        setAccounts(
          (Array.isArray(items) ? items : []).map((x: { id: string; name: string }) => ({
            id: x.id,
            label: x.name,
          }))
        );
      }

      if (contractsRes.ok) {
        const ct = await contractsRes.json();
        const items = ct.data || ct;
        setContractOptions(
          (Array.isArray(items) ? items : []).map(
            (x: { id: string; contractName: string }) => ({
              id: x.id,
              label: x.contractName,
            })
          )
        );
      }
    } catch {
      // Silent
    }
  }, []);

  // ---------------------------------------------------------------------------
  // Effects
  // ---------------------------------------------------------------------------

  useEffect(() => {
    fetchBusinessTasks();
  }, [fetchBusinessTasks]);

  useEffect(() => {
    fetchPersonalTasks();
  }, [fetchPersonalTasks]);

  useEffect(() => {
    fetchStats();
  }, [fetchStats]);

  // Build users list from business tasks assignees
  useEffect(() => {
    const userMap = new Map<string, string>();
    businessTasks.forEach((t) => {
      if (t.assignee) {
        userMap.set(t.assignee.id!, t.assignee.name || t.assignee.email || "Unknown");
      }
    });
    setUsers(Array.from(userMap.entries()).map(([id, name]) => ({ id, name })));
  }, [businessTasks]);

  // ---------------------------------------------------------------------------
  // Quick complete
  // ---------------------------------------------------------------------------

  async function toggleComplete(task: Task) {
    const newStatus = task.status === "completed" ? "pending" : "completed";
    try {
      const res = await fetch(`/api/tasks/${task.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status: newStatus }),
      });
      if (!res.ok) throw new Error("Failed to update");
      toast({
        title: newStatus === "completed" ? "Completed" : "Reopened",
        description: `Task "${task.title}" ${newStatus === "completed" ? "marked complete" : "reopened"}.`,
      });
      if (task.taskType === "business") {
        fetchBusinessTasks();
      } else {
        fetchPersonalTasks();
      }
      fetchStats();
    } catch {
      toast({ title: "Error", description: "Failed to update task.", variant: "destructive" });
    }
  }

  // ---------------------------------------------------------------------------
  // Delete task
  // ---------------------------------------------------------------------------

  async function deleteTask(taskId: string, taskType: string) {
    try {
      const res = await fetch(`/api/tasks/${taskId}`, { method: "DELETE" });
      if (!res.ok) throw new Error("Failed to delete");
      toast({ title: "Deleted", description: "Task deleted." });
      if (taskType === "business") {
        fetchBusinessTasks();
      } else {
        fetchPersonalTasks();
      }
      fetchStats();
    } catch {
      toast({ title: "Error", description: "Failed to delete task.", variant: "destructive" });
    }
  }

  // ---------------------------------------------------------------------------
  // Create business task
  // ---------------------------------------------------------------------------

  function openCreateDialog() {
    setFormTitle("");
    setFormDescription("");
    setFormAssignedTo(currentUserId || "");
    setFormPriority("medium");
    setFormDueDate("");
    setFormDealId("");
    setFormLeadId("");
    setFormContactId("");
    setFormAccountId("");
    setFormContractId("");
    fetchLinkOptions();
    setCreateOpen(true);
  }

  async function handleCreateTask() {
    if (!formTitle.trim()) {
      toast({ title: "Validation", description: "Title is required.", variant: "destructive" });
      return;
    }
    if (!formAssignedTo) {
      toast({ title: "Validation", description: "Assign to is required.", variant: "destructive" });
      return;
    }

    setSaving(true);
    try {
      const payload: Record<string, unknown> = {
        title: formTitle.trim(),
        description: formDescription.trim() || null,
        assignedTo: formAssignedTo,
        createdBy: currentUserId,
        taskType: "business",
        priority: formPriority,
        dueDate: formDueDate || null,
        dealId: formDealId || null,
        leadId: formLeadId || null,
        contactId: formContactId || null,
        accountId: formAccountId || null,
        contractId: formContractId || null,
      };

      const res = await fetch("/api/tasks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || "Failed to create task");
      }

      toast({ title: "Success", description: "Task created." });
      setCreateOpen(false);
      fetchBusinessTasks();
      fetchStats();
    } catch (err) {
      toast({
        title: "Error",
        description: err instanceof Error ? err.message : "Failed to create task.",
        variant: "destructive",
      });
    } finally {
      setSaving(false);
    }
  }

  // ---------------------------------------------------------------------------
  // Add personal to-do
  // ---------------------------------------------------------------------------

  async function handleAddTodo() {
    if (!newTodoText.trim()) return;
    if (!currentUserId) return;

    setAddingTodo(true);
    try {
      const payload: Record<string, unknown> = {
        title: newTodoText.trim(),
        assignedTo: currentUserId,
        createdBy: currentUserId,
        taskType: "personal",
        priority: "medium",
        dueDate: newTodoDueDate || null,
      };

      const res = await fetch("/api/tasks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (!res.ok) throw new Error("Failed to create");

      setNewTodoText("");
      setNewTodoDueDate("");
      fetchPersonalTasks();
      fetchStats();
    } catch {
      toast({ title: "Error", description: "Failed to add to-do.", variant: "destructive" });
    } finally {
      setAddingTodo(false);
    }
  }

  // ---------------------------------------------------------------------------
  // Drag reorder (personal to-do) -- local state only
  // ---------------------------------------------------------------------------

  function handleDragEnd(result: DropResult) {
    if (!result.destination) return;
    const items = Array.from(personalTasks);
    const [reordered] = items.splice(result.source.index, 1);
    items.splice(result.destination.index, 0, reordered);
    setPersonalTasks(items);
  }

  // ---------------------------------------------------------------------------
  // Sorting toggle
  // ---------------------------------------------------------------------------

  function toggleSort(field: string) {
    if (sortBy === field) {
      setSortOrder((o) => (o === "asc" ? "desc" : "asc"));
    } else {
      setSortBy(field);
      setSortOrder("asc");
    }
  }

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  return (
    <>
      {/* Page header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            <CheckSquare className="h-6 w-6" />
            Tasks
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Manage business tasks and personal to-dos.
          </p>
        </div>
      </div>

      {/* Stats cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-1.5">
              <ListTodo className="h-4 w-4" />
              Total Active
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-2xl font-bold">{statsTotal}</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-red-600 flex items-center gap-1.5">
              <AlertTriangle className="h-4 w-4" />
              Overdue
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-2xl font-bold text-red-600">{statsOverdue}</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-amber-600 flex items-center gap-1.5">
              <Clock className="h-4 w-4" />
              Due Today
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-2xl font-bold text-amber-600">{statsDueToday}</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-green-600 flex items-center gap-1.5">
              <CheckCircle className="h-4 w-4" />
              Completed This Week
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-2xl font-bold text-green-600">{statsCompletedWeek}</p>
          </CardContent>
        </Card>
      </div>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="business" className="gap-1.5">
            <Briefcase className="h-3.5 w-3.5" />
            Business Tasks
          </TabsTrigger>
          <TabsTrigger value="personal" className="gap-1.5">
            <ListTodo className="h-3.5 w-3.5" />
            Personal To-Do
          </TabsTrigger>
        </TabsList>

        {/* ================================================================ */}
        {/* Business Tasks Tab */}
        {/* ================================================================ */}
        <TabsContent value="business">
          {/* Filters & actions bar */}
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between mb-4 mt-2">
            <div className="flex flex-wrap items-center gap-2">
              {/* Assigned to */}
              <Select value={filterAssignedTo} onValueChange={setFilterAssignedTo}>
                <SelectTrigger className="w-[160px] h-8 text-xs">
                  <User className="h-3 w-3 mr-1" />
                  <SelectValue placeholder="Assigned to" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Users</SelectItem>
                  {users.map((u) => (
                    <SelectItem key={u.id} value={u.id}>{u.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>

              {/* Status */}
              <Select value={filterStatus} onValueChange={setFilterStatus}>
                <SelectTrigger className="w-[140px] h-8 text-xs">
                  <Filter className="h-3 w-3 mr-1" />
                  <SelectValue placeholder="Status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Statuses</SelectItem>
                  {Object.entries(STATUS_LABELS).map(([key, label]) => (
                    <SelectItem key={key} value={key}>{label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>

              {/* Priority */}
              <Select value={filterPriority} onValueChange={setFilterPriority}>
                <SelectTrigger className="w-[130px] h-8 text-xs">
                  <SelectValue placeholder="Priority" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Priorities</SelectItem>
                  {Object.entries(PRIORITY_LABELS).map(([key, label]) => (
                    <SelectItem key={key} value={key}>{label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>

              {/* Overdue toggle */}
              <Button
                variant={filterOverdue ? "default" : "outline"}
                size="sm"
                className="h-8 text-xs gap-1"
                onClick={() => setFilterOverdue(!filterOverdue)}
              >
                <AlertTriangle className="h-3 w-3" />
                Overdue
              </Button>

              {/* Sort */}
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="outline" size="sm" className="h-8 text-xs gap-1">
                    <ArrowUpDown className="h-3 w-3" />
                    Sort
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                  <DropdownMenuItem onClick={() => toggleSort("dueDate")}>
                    Due Date {sortBy === "dueDate" && (sortOrder === "asc" ? "(earliest)" : "(latest)")}
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => toggleSort("priorityWeight")}>
                    Priority {sortBy === "priorityWeight" && (sortOrder === "desc" ? "(highest)" : "(lowest)")}
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => toggleSort("createdAt")}>
                    Created {sortBy === "createdAt" && (sortOrder === "desc" ? "(newest)" : "(oldest)")}
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>

            <Button onClick={openCreateDialog} className="gap-2" size="sm">
              <Plus className="h-4 w-4" />
              New Task
            </Button>
          </div>

          {/* Table */}
          {businessLoading ? (
            <div className="flex items-center justify-center py-20">
              <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
            </div>
          ) : businessTasks.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-muted-foreground">
              <CheckSquare className="h-10 w-10 mb-2" />
              <p className="text-sm">No tasks found.</p>
            </div>
          ) : (
            <div className="border rounded-lg overflow-hidden">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-10" />
                    <TableHead>Title</TableHead>
                    <TableHead>Linked Record</TableHead>
                    <TableHead>Assigned To</TableHead>
                    <TableHead className="cursor-pointer" onClick={() => toggleSort("dueDate")}>
                      Due Date
                    </TableHead>
                    <TableHead className="cursor-pointer" onClick={() => toggleSort("priorityWeight")}>
                      Priority
                    </TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="w-10" />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {businessTasks.map((task) => {
                    const linked = getLinkedRecordLabel(task);
                    const overdue = isOverdue(task);
                    const dueToday = isDueToday(task);

                    return (
                      <TableRow
                        key={task.id}
                        className={cn(
                          task.status === "completed" && "opacity-60"
                        )}
                      >
                        {/* Checkbox */}
                        <TableCell>
                          <Checkbox
                            checked={task.status === "completed"}
                            onCheckedChange={() => toggleComplete(task)}
                          />
                        </TableCell>

                        {/* Title */}
                        <TableCell>
                          <span
                            className={cn(
                              "font-medium text-sm",
                              task.status === "completed" && "line-through text-muted-foreground"
                            )}
                          >
                            {task.title}
                          </span>
                          {task.description && (
                            <p className="text-xs text-muted-foreground truncate max-w-[300px]">
                              {task.description}
                            </p>
                          )}
                        </TableCell>

                        {/* Linked record */}
                        <TableCell>
                          {linked ? (
                            <Badge variant="outline" className="text-xs">
                              {linked.type}: {linked.name}
                            </Badge>
                          ) : (
                            <span className="text-xs text-muted-foreground">-</span>
                          )}
                        </TableCell>

                        {/* Assigned to */}
                        <TableCell>
                          <span className="text-sm">
                            {task.assignee?.name || "Unassigned"}
                          </span>
                        </TableCell>

                        {/* Due date */}
                        <TableCell>
                          {task.dueDate ? (
                            <span
                              className={cn(
                                "text-sm",
                                overdue && "text-red-600 font-medium",
                                dueToday && !overdue && "text-amber-600 font-medium"
                              )}
                            >
                              {format(parseISO(task.dueDate), "d MMM yyyy")}
                              {overdue && (
                                <Tooltip>
                                  <TooltipTrigger asChild>
                                    <AlertTriangle className="inline h-3.5 w-3.5 ml-1 text-red-500" />
                                  </TooltipTrigger>
                                  <TooltipContent>Overdue</TooltipContent>
                                </Tooltip>
                              )}
                            </span>
                          ) : (
                            <span className="text-xs text-muted-foreground">No date</span>
                          )}
                        </TableCell>

                        {/* Priority */}
                        <TableCell>
                          <Badge
                            variant="outline"
                            className={cn("text-xs capitalize", PRIORITY_COLORS[task.priority])}
                          >
                            {PRIORITY_LABELS[task.priority] || task.priority}
                          </Badge>
                        </TableCell>

                        {/* Status */}
                        <TableCell>
                          <Badge
                            variant={task.status === "completed" ? "secondary" : "outline"}
                            className="text-xs"
                          >
                            {STATUS_LABELS[task.status] || task.status}
                          </Badge>
                        </TableCell>

                        {/* Delete */}
                        <TableCell>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-7 w-7 text-muted-foreground hover:text-red-600"
                            onClick={() => deleteTask(task.id, "business")}
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </Button>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          )}
        </TabsContent>

        {/* ================================================================ */}
        {/* Personal To-Do Tab */}
        {/* ================================================================ */}
        <TabsContent value="personal">
          {/* Add new to-do */}
          <div className="flex items-center gap-2 mb-4 mt-2">
            <Input
              placeholder="Add a new to-do..."
              value={newTodoText}
              onChange={(e) => setNewTodoText(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") handleAddTodo();
              }}
              className="flex-1"
            />
            <Input
              type="date"
              value={newTodoDueDate}
              onChange={(e) => setNewTodoDueDate(e.target.value)}
              className="w-[160px]"
              placeholder="Due date"
            />
            <Button
              onClick={handleAddTodo}
              disabled={!newTodoText.trim() || addingTodo}
              size="sm"
              className="gap-1"
            >
              {addingTodo ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Plus className="h-4 w-4" />
              )}
              Add
            </Button>
          </div>

          {/* To-do list */}
          {personalLoading ? (
            <div className="flex items-center justify-center py-20">
              <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
            </div>
          ) : personalTasks.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-muted-foreground">
              <ListTodo className="h-10 w-10 mb-2" />
              <p className="text-sm">No personal to-dos yet. Add one above!</p>
            </div>
          ) : (
            <DragDropContext onDragEnd={handleDragEnd}>
              <Droppable droppableId="personal-todos">
                {(provided) => (
                  <div
                    ref={provided.innerRef}
                    {...provided.droppableProps}
                    className="space-y-1"
                  >
                    {personalTasks.map((task, index) => (
                      <Draggable key={task.id} draggableId={task.id} index={index}>
                        {(provided, snapshot) => (
                          <div
                            ref={provided.innerRef}
                            {...provided.draggableProps}
                            className={cn(
                              "flex items-center gap-3 px-3 py-2.5 rounded-lg border bg-background transition-colors",
                              snapshot.isDragging && "shadow-lg border-primary/30",
                              task.status === "completed" && "opacity-60"
                            )}
                          >
                            {/* Drag handle */}
                            <div
                              {...provided.dragHandleProps}
                              className="cursor-grab text-muted-foreground hover:text-foreground"
                            >
                              <GripVertical className="h-4 w-4" />
                            </div>

                            {/* Checkbox */}
                            <Checkbox
                              checked={task.status === "completed"}
                              onCheckedChange={() => toggleComplete(task)}
                            />

                            {/* Title */}
                            <span
                              className={cn(
                                "flex-1 text-sm",
                                task.status === "completed" && "line-through text-muted-foreground"
                              )}
                            >
                              {task.title}
                            </span>

                            {/* Due date */}
                            {task.dueDate && (
                              <span
                                className={cn(
                                  "text-xs text-muted-foreground",
                                  isOverdue(task) && "text-red-600 font-medium",
                                  isDueToday(task) && !isOverdue(task) && "text-amber-600 font-medium"
                                )}
                              >
                                {format(parseISO(task.dueDate), "d MMM")}
                              </span>
                            )}

                            {/* Delete */}
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-7 w-7 text-muted-foreground hover:text-red-600 shrink-0"
                              onClick={() => deleteTask(task.id, "personal")}
                            >
                              <Trash2 className="h-3.5 w-3.5" />
                            </Button>
                          </div>
                        )}
                      </Draggable>
                    ))}
                    {provided.placeholder}
                  </div>
                )}
              </Droppable>
            </DragDropContext>
          )}
        </TabsContent>
      </Tabs>

      {/* ================================================================ */}
      {/* Create Business Task Dialog */}
      {/* ================================================================ */}
      <Dialog open={createOpen} onOpenChange={setCreateOpen}>
        <DialogContent className="sm:max-w-[520px]">
          <DialogHeader>
            <DialogTitle>New Business Task</DialogTitle>
            <DialogDescription>
              Create a new task and optionally link it to a record.
            </DialogDescription>
          </DialogHeader>

          <div className="grid gap-4 py-2">
            {/* Title */}
            <div className="grid gap-1.5">
              <Label htmlFor="task-title">Title *</Label>
              <Input
                id="task-title"
                value={formTitle}
                onChange={(e) => setFormTitle(e.target.value)}
                placeholder="Task title"
              />
            </div>

            {/* Description */}
            <div className="grid gap-1.5">
              <Label htmlFor="task-desc">Description</Label>
              <Textarea
                id="task-desc"
                value={formDescription}
                onChange={(e) => setFormDescription(e.target.value)}
                placeholder="Optional description..."
                rows={3}
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              {/* Assign to */}
              <div className="grid gap-1.5">
                <Label>Assign to *</Label>
                <Select value={formAssignedTo} onValueChange={setFormAssignedTo}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select user" />
                  </SelectTrigger>
                  <SelectContent>
                    {currentUserId && (
                      <SelectItem value={currentUserId}>
                        {session?.user?.name || "Me"}
                      </SelectItem>
                    )}
                    {users
                      .filter((u) => u.id !== currentUserId)
                      .map((u) => (
                        <SelectItem key={u.id} value={u.id}>{u.name}</SelectItem>
                      ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Priority */}
              <div className="grid gap-1.5">
                <Label>Priority</Label>
                <Select value={formPriority} onValueChange={setFormPriority}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {Object.entries(PRIORITY_LABELS).map(([key, label]) => (
                      <SelectItem key={key} value={key}>{label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* Due date */}
            <div className="grid gap-1.5">
              <Label htmlFor="task-due">Due Date</Label>
              <Input
                id="task-due"
                type="date"
                value={formDueDate}
                onChange={(e) => setFormDueDate(e.target.value)}
              />
            </div>

            <Separator />

            {/* Link to records */}
            <p className="text-xs font-medium text-muted-foreground">Link to record (optional)</p>

            <div className="grid grid-cols-2 gap-3">
              <div className="grid gap-1.5">
                <Label className="text-xs">Deal</Label>
                <Select value={formDealId} onValueChange={setFormDealId}>
                  <SelectTrigger className="h-8 text-xs">
                    <SelectValue placeholder="None" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">None</SelectItem>
                    {deals.map((d) => (
                      <SelectItem key={d.id} value={d.id}>{d.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-1.5">
                <Label className="text-xs">Lead</Label>
                <Select value={formLeadId} onValueChange={setFormLeadId}>
                  <SelectTrigger className="h-8 text-xs">
                    <SelectValue placeholder="None" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">None</SelectItem>
                    {leads.map((l) => (
                      <SelectItem key={l.id} value={l.id}>{l.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-1.5">
                <Label className="text-xs">Contact</Label>
                <Select value={formContactId} onValueChange={setFormContactId}>
                  <SelectTrigger className="h-8 text-xs">
                    <SelectValue placeholder="None" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">None</SelectItem>
                    {contacts.map((c) => (
                      <SelectItem key={c.id} value={c.id}>{c.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-1.5">
                <Label className="text-xs">Account</Label>
                <Select value={formAccountId} onValueChange={setFormAccountId}>
                  <SelectTrigger className="h-8 text-xs">
                    <SelectValue placeholder="None" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">None</SelectItem>
                    {accounts.map((a) => (
                      <SelectItem key={a.id} value={a.id}>{a.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-1.5 col-span-2">
                <Label className="text-xs">Contract</Label>
                <Select value={formContractId} onValueChange={setFormContractId}>
                  <SelectTrigger className="h-8 text-xs">
                    <SelectValue placeholder="None" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">None</SelectItem>
                    {contractOptions.map((ct) => (
                      <SelectItem key={ct.id} value={ct.id}>{ct.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateOpen(false)} disabled={saving}>
              Cancel
            </Button>
            <Button onClick={handleCreateTask} disabled={saving}>
              {saving && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              Create Task
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
