import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { Prisma, TaskStatus, Priority, TaskType } from "@prisma/client";
import { sendNotificationEmail } from "@/lib/notification-email";

// Priority weight map for sorting
const PRIORITY_WEIGHT: Record<string, number> = {
  urgent: 4,
  high: 3,
  medium: 2,
  low: 1,
};

// GET /api/tasks — List tasks with filters and pagination
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);

    // Pagination
    const page = Math.max(1, parseInt(searchParams.get("page") || "1", 10));
    const limit = Math.min(
      100,
      Math.max(1, parseInt(searchParams.get("limit") || "20", 10))
    );
    const skip = (page - 1) * limit;

    // Sorting
    const sortBy = searchParams.get("sortBy") || "createdAt";
    const sortOrder = searchParams.get("sortOrder") === "asc" ? "asc" : "desc";

    // Build where clause
    const where: Prisma.TaskWhereInput = {};

    // Filter by assignedTo
    const assignedTo = searchParams.get("assignedTo");
    if (assignedTo) {
      where.assignedTo = assignedTo;
    }

    // Filter by status
    const status = searchParams.get("status");
    if (status) {
      where.status = status as TaskStatus;
    }

    // Filter by priority
    const priority = searchParams.get("priority");
    if (priority) {
      where.priority = priority as Priority;
    }

    // Filter by taskType ('business' or 'personal') — for the two-tab UI
    const taskType = searchParams.get("taskType");
    if (taskType) {
      where.taskType = taskType as TaskType;
    }

    // Filter by autoGenerated
    const autoGenerated = searchParams.get("autoGenerated");
    if (autoGenerated === "true") {
      where.autoGenerated = true;
    } else if (autoGenerated === "false") {
      where.autoGenerated = false;
    }

    // Filter by sourceWorkflow
    const sourceWorkflow = searchParams.get("sourceWorkflow");
    if (sourceWorkflow) {
      where.sourceWorkflow = sourceWorkflow;
    }

    // Filter by linked entity
    const dealId = searchParams.get("dealId");
    if (dealId) {
      where.dealId = dealId;
    }

    const leadId = searchParams.get("leadId");
    if (leadId) {
      where.leadId = leadId;
    }

    const contractId = searchParams.get("contractId");
    if (contractId) {
      where.contractId = contractId;
    }

    const subcontractorId = searchParams.get("subcontractorId");
    if (subcontractorId) {
      where.subcontractorId = subcontractorId;
    }

    const accountId = searchParams.get("accountId");
    if (accountId) {
      where.accountId = accountId;
    }

    const contactId = searchParams.get("contactId");
    if (contactId) {
      where.contactId = contactId;
    }

    // Filter by dueDate range
    const dueDateFrom = searchParams.get("dueDateFrom");
    const dueDateTo = searchParams.get("dueDateTo");
    if (dueDateFrom || dueDateTo) {
      where.dueDate = {};
      if (dueDateFrom) {
        where.dueDate.gte = new Date(dueDateFrom);
      }
      if (dueDateTo) {
        where.dueDate.lte = new Date(dueDateTo);
      }
    }

    // Filter for overdue tasks (due before now and not completed/cancelled)
    const overdue = searchParams.get("overdue");
    if (overdue === "true") {
      where.dueDate = { lt: new Date() };
      where.status = { in: ["pending", "in_progress"] };
    }

    // Determine orderBy — support priority weight sorting
    let orderBy: Prisma.TaskOrderByWithRelationInput;
    if (sortBy === "priorityWeight") {
      // Sort by priority enum order: urgent > high > medium > low
      orderBy = { priority: sortOrder };
    } else {
      orderBy = { [sortBy]: sortOrder };
    }

    // Execute count and findMany in parallel
    const [total, tasks] = await Promise.all([
      prisma.task.count({ where }),
      prisma.task.findMany({
        where,
        include: {
          assignee: {
            select: { id: true, name: true, email: true, avatarUrl: true },
          },
          creator: {
            select: { id: true, name: true },
          },
          deal: {
            select: { id: true, name: true },
          },
          lead: {
            select: { id: true, companyName: true, contactName: true },
          },
          contact: {
            select: { id: true, firstName: true, lastName: true },
          },
          account: {
            select: { id: true, name: true },
          },
          contract: {
            select: { id: true, contractName: true, status: true },
          },
          subcontractor: {
            select: { id: true, contactName: true, companyName: true },
          },
        },
        orderBy,
        skip,
        take: limit,
      }),
    ]);

    // If sorting by priorityWeight, apply in-memory sort for precise weight ordering
    let sortedTasks = tasks;
    if (sortBy === "priorityWeight") {
      sortedTasks = [...tasks].sort((a, b) => {
        const weightA = PRIORITY_WEIGHT[a.priority] ?? 0;
        const weightB = PRIORITY_WEIGHT[b.priority] ?? 0;
        return sortOrder === "desc" ? weightB - weightA : weightA - weightB;
      });
    }

    return NextResponse.json({
      data: sortedTasks,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    });
  } catch (error) {
    console.error("GET /api/tasks error:", error);
    return NextResponse.json(
      { error: "Failed to fetch tasks" },
      { status: 500 }
    );
  }
}

// POST /api/tasks — Create a task
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    // Validate required fields
    if (!body.title) {
      return NextResponse.json(
        { error: "title is required" },
        { status: 400 }
      );
    }

    if (!body.assignedTo) {
      return NextResponse.json(
        { error: "assignedTo is required" },
        { status: 400 }
      );
    }

    if (!body.createdBy) {
      return NextResponse.json(
        { error: "createdBy is required" },
        { status: 400 }
      );
    }

    const task = await prisma.task.create({
      data: {
        title: body.title,
        description: body.description,
        assignedTo: body.assignedTo,
        createdBy: body.createdBy,
        taskType: body.taskType,
        priority: body.priority,
        dealId: body.dealId,
        leadId: body.leadId,
        contactId: body.contactId,
        accountId: body.accountId,
        contractId: body.contractId,
        subcontractorId: body.subcontractorId,
        dueDate: body.dueDate ? new Date(body.dueDate) : undefined,
        status: body.status,
        autoGenerated: body.autoGenerated,
        sourceWorkflow: body.sourceWorkflow,
        isRecurring: body.isRecurring ?? false,
        recurrenceRule: body.recurrenceRule,
        recurringParentId: body.recurringParentId,
        notes: body.notes,
      },
      include: {
        assignee: {
          select: { id: true, name: true, email: true, avatarUrl: true },
        },
        creator: {
          select: { id: true, name: true },
        },
        deal: {
          select: { id: true, name: true },
        },
        lead: {
          select: { id: true, companyName: true, contactName: true },
        },
        contact: {
          select: { id: true, firstName: true, lastName: true },
        },
        account: {
          select: { id: true, name: true },
        },
        contract: {
          select: { id: true, contractName: true, status: true },
        },
        subcontractor: {
          select: { id: true, contactName: true, companyName: true },
        },
      },
    });

    // Create notification when task is assigned to a different user
    if (body.assignedTo && body.createdBy && body.assignedTo !== body.createdBy) {
      try {
        const creator = await prisma.user.findUnique({
          where: { id: body.createdBy },
          select: { name: true },
        });
        const notifTitle = "New Task Assigned";
        const notifMessage = `${creator?.name || "Someone"} assigned you a task: "${body.title}"`;
        await prisma.notification.create({
          data: {
            userId: body.assignedTo,
            title: notifTitle,
            message: notifMessage,
            notificationType: "task_assigned",
            linkUrl: "/tasks",
            entityType: "task",
            entityId: task.id,
          },
        });
        sendNotificationEmail(body.assignedTo, notifTitle, notifMessage, "/tasks").catch(() => {});
      } catch (notifError) {
        console.error("Failed to create task assignment notification:", notifError);
      }
    }

    return NextResponse.json({ data: task }, { status: 201 });
  } catch (error) {
    console.error("POST /api/tasks error:", error);

    if (error instanceof Prisma.PrismaClientValidationError) {
      return NextResponse.json(
        { error: "Invalid task data provided" },
        { status: 400 }
      );
    }

    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      if (error.code === "P2025") {
        return NextResponse.json(
          { error: "One or more linked records not found (e.g. assignee, deal)" },
          { status: 400 }
        );
      }
      if (error.code === "P2003") {
        return NextResponse.json(
          { error: "Foreign key constraint failed — linked record does not exist" },
          { status: 400 }
        );
      }
    }

    return NextResponse.json(
      { error: "Failed to create task" },
      { status: 500 }
    );
  }
}
