import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { Prisma } from "@prisma/client";

interface RouteParams {
  params: Promise<{ id: string }>;
}

// ── GET /api/issues/[id] ───────────────────────────────────────────

export async function GET(request: NextRequest, { params }: RouteParams) {
  try {
    const { id } = await params;

    const issue = await prisma.issue.findUnique({
      where: { id },
      include: {
        contract: {
          select: {
            id: true,
            contractName: true,
            status: true,
            accountId: true,
            account: { select: { id: true, name: true } },
          },
        },
        account: {
          select: { id: true, name: true },
        },
        assignee: {
          select: { id: true, name: true, email: true, avatarUrl: true },
        },
      },
    });

    if (!issue) {
      return NextResponse.json(
        { error: "Issue not found" },
        { status: 404 }
      );
    }

    return NextResponse.json({ data: issue });
  } catch (error) {
    console.error("GET /api/issues/[id] error:", error);
    return NextResponse.json(
      { error: "Failed to fetch issue" },
      { status: 500 }
    );
  }
}

// ── PUT /api/issues/[id] ───────────────────────────────────────────

export async function PUT(request: NextRequest, { params }: RouteParams) {
  try {
    const { id } = await params;
    const body = await request.json();

    const existing = await prisma.issue.findUnique({
      where: { id },
      select: {
        id: true,
        title: true,
        contractId: true,
        reportedBy: true,
        firstResponseAt: true,
        resolvedAt: true,
        slaResponseTarget: true,
        status: true,
        assignedTo: true,
      },
    });

    if (!existing) {
      return NextResponse.json(
        { error: "Issue not found" },
        { status: 404 }
      );
    }

    // Strip immutable fields
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { id: _id, createdAt: _ca, updatedAt: _ua, ...updateData } = body;

    const sideEffects: Promise<unknown>[] = [];

    // Special handling: firstResponseAt being set for the first time
    if (body.firstResponseAt && !existing.firstResponseAt) {
      const responseTime = new Date(body.firstResponseAt);
      if (
        existing.slaResponseTarget &&
        responseTime > existing.slaResponseTarget
      ) {
        updateData.slaBreached = true;
      }
    }

    // Special handling: resolvedAt being set
    if (body.resolvedAt && !existing.resolvedAt) {
      const resolvedTime = new Date(body.resolvedAt);
      updateData.followUpDueAt = new Date(
        resolvedTime.getTime() + 48 * 60 * 60 * 1000
      );

      // Find admin user for task creation
      const adminUser = await prisma.user.findFirst({
        where: { role: "admin" },
        select: { id: true },
      });

      if (adminUser) {
        sideEffects.push(
          prisma.task.create({
            data: {
              title: `48hr follow-up: ${existing.title}`,
              description: `Follow up on resolved issue to confirm client satisfaction. Issue was resolved at ${resolvedTime.toISOString()}.`,
              assignedTo: existing.assignedTo ?? adminUser.id,
              createdBy: adminUser.id,
              priority: "medium",
              contractId: existing.contractId,
              dueDate: updateData.followUpDueAt,
              autoGenerated: true,
              sourceWorkflow: "issue_follow_up",
            },
          })
        );
      }
    }

    // Special handling: status changing to 'resolved' or 'closed'
    if (
      (body.status === "resolved" || body.status === "closed") &&
      existing.status !== "resolved" &&
      existing.status !== "closed"
    ) {
      // Notify original reporter (create notification for admin since reportedBy is a string name)
      const adminUser = await prisma.user.findFirst({
        where: { role: "admin" },
        select: { id: true },
      });

      if (adminUser) {
        sideEffects.push(
          prisma.notification.create({
            data: {
              userId: adminUser.id,
              title: `Issue ${body.status}: ${existing.title}`,
              message: `Issue "${existing.title}" has been ${body.status}. Reported by: ${existing.reportedBy ?? "Unknown"}.`,
              notificationType: "issue_raised",
              linkUrl: `/issues/${id}`,
              entityType: "issue",
              entityId: id,
            },
          })
        );
      }
    }

    const issue = await prisma.issue.update({
      where: { id },
      data: updateData,
      include: {
        contract: {
          select: {
            id: true,
            contractName: true,
            status: true,
            account: { select: { id: true, name: true } },
          },
        },
        account: {
          select: { id: true, name: true },
        },
        assignee: {
          select: { id: true, name: true, email: true, avatarUrl: true },
        },
      },
    });

    await Promise.all(sideEffects);

    return NextResponse.json({ data: issue });
  } catch (error) {
    console.error("PUT /api/issues/[id] error:", error);

    if (error instanceof Prisma.PrismaClientKnownRequestError) {
      if (error.code === "P2025") {
        return NextResponse.json(
          { error: "Issue not found" },
          { status: 404 }
        );
      }
    }

    if (error instanceof Prisma.PrismaClientValidationError) {
      return NextResponse.json(
        { error: "Invalid update data provided" },
        { status: 400 }
      );
    }

    return NextResponse.json(
      { error: "Failed to update issue" },
      { status: 500 }
    );
  }
}

// ── DELETE /api/issues/[id] ─────────────────────────────────────────

export async function DELETE(request: NextRequest, { params }: RouteParams) {
  try {
    const { id } = await params;

    const existing = await prisma.issue.findUnique({
      where: { id },
      select: { id: true },
    });

    if (!existing) {
      return NextResponse.json(
        { error: "Issue not found" },
        { status: 404 }
      );
    }

    await prisma.issue.delete({ where: { id } });

    return NextResponse.json(
      { message: "Issue deleted successfully" },
      { status: 200 }
    );
  } catch (error) {
    console.error("DELETE /api/issues/[id] error:", error);
    return NextResponse.json(
      { error: "Failed to delete issue" },
      { status: 500 }
    );
  }
}
